# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63241d32416b336ff62ebbfb0674cfbeac3a340fbff1fe5e5a9f242774d3db490dda0040f5265cbfc3b19823168ce6f2a012e0d19b883b60d733bd70d3a9270b

test:
  secret_key_base: bc7ec97bb1577b24edd11ab2048eae2f8b8d021d969c0c9de745f74b8883593e3a112a3607a79205893d0cec6a61269e5aaf85cc9c9f33d8b1d51ed725231732

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
